export const mockSettings = {
  id: "1",
  free_gift_threshold: 1499,
  free_gift_title: "Free Mystery Crochet Gift",
  free_gift_value_label: "Worth ₹400",
  is_free_gift_active: true
};

export const mockCategories = [
  { id: "1", name: "Florals", slug: "florals" },
  { id: "2", name: "Wearables & Bags", slug: "wearables" },
  { id: "3", name: "Plushies", slug: "plushies" },
  { id: "4", name: "Decor", slug: "decor" },
];

export const mockProducts = [
  {
    id: "1",
    slug: "sample-product-1",
    title: "Handmade Crochet Sample 1",
    description: "A beautiful handmade crochet piece made with soft pastel yarn.",
    price: 1299,
    images: ["/my images/img 1.jpg"],
    product_type: "ready_to_ship",
    in_stock: true,
    is_featured: true,
    category_id: "1",
    categories: { slug: "florals", name: "Florals" },
  },
  {
    id: "2",
    slug: "sample-product-2",
    title: "Handmade Crochet Sample 2",
    description: "A beautiful handmade crochet piece made with soft pastel yarn.",
    price: 1499,
    images: ["/my images/img 2.jpg"],
    product_type: "made_to_order",
    in_stock: true,
    is_featured: true,
    category_id: "2",
    categories: { slug: "wearables", name: "Wearables & Bags" },
  },
  {
    id: "3",
    slug: "sample-product-3",
    title: "Handmade Crochet Sample 3",
    description: "A beautiful handmade crochet piece made with soft pastel yarn.",
    price: 999,
    images: ["/my images/img 3.jpg"],
    product_type: "ready_to_ship",
    in_stock: true,
    is_featured: true,
    category_id: "3",
    categories: { slug: "plushies", name: "Plushies" },
  },
  {
    id: "4",
    slug: "sample-product-4",
    title: "Handmade Crochet Sample 4",
    description: "A beautiful handmade crochet piece made with soft pastel yarn.",
    price: 1999,
    images: ["/my images/img 4.jpg"],
    product_type: "made_to_order",
    in_stock: true,
    is_featured: true,
    category_id: "4",
    categories: { slug: "decor", name: "Decor" },
  },
  {
    id: "5",
    slug: "sample-product-5",
    title: "Handmade Crochet Sample 5",
    description: "A beautiful handmade crochet piece made with soft pastel yarn.",
    price: 849,
    images: ["/my images/img 5.jpg"],
    product_type: "ready_to_ship",
    in_stock: true,
    is_featured: true,
    category_id: "1",
    categories: { slug: "florals", name: "Florals" },
  },
  {
    id: "6",
    slug: "sample-product-6",
    title: "Handmade Crochet Sample 6",
    description: "A beautiful handmade crochet piece made with soft pastel yarn.",
    price: 1749,
    images: ["/my images/img 6.jpg"],
    product_type: "made_to_order",
    in_stock: true,
    is_featured: true,
    category_id: "2",
    categories: { slug: "wearables", name: "Wearables & Bags" },
  },
  {
    id: "7",
    slug: "sample-product-7",
    title: "Handmade Crochet Sample 7",
    description: "A beautiful handmade crochet piece made with soft pastel yarn.",
    price: 1199,
    images: ["/my images/img 7.jpg"],
    product_type: "ready_to_ship",
    in_stock: true,
    is_featured: false,
    category_id: "1",
    categories: { slug: "florals", name: "Florals" },
  },
  {
    id: "8",
    slug: "sample-product-8",
    title: "Handmade Crochet Sample 8",
    description: "A beautiful handmade crochet piece made with soft pastel yarn.",
    price: 2199,
    images: ["/my images/img 8.jpg"],
    product_type: "made_to_order",
    in_stock: true,
    is_featured: false,
    category_id: "2",
    categories: { slug: "wearables", name: "Wearables & Bags" },
  }
];

